In [38]:
import pandas as pd
import numpy as np
url = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(url, encoding='latin-1', sep=';')
df

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37583,159,3,2026,2026m03,35,4,Cachoeiras de Macacu,3300803,Interior,3,...,5.0,0.0,26,1,0,0,0,0,156,2
37584,165,3,2026,2026m03,33,5,Mangaratiba,3302601,Interior,1,...,13.0,0.0,33,1,0,0,0,0,240,2
37585,166,3,2026,2026m03,33,5,Angra dos Reis,3300100,Interior,2,...,14.0,1.0,91,10,0,0,0,0,744,2
37586,167,3,2026,2026m03,43,5,Paraty,3303807,Interior,0,...,7.0,0.0,25,1,0,0,0,0,259,2
37587,168,3,2026,2026m03,28,5,Rio Claro,3304409,Interior,0,...,1.0,0.0,8,0,0,0,0,0,52,2

In [39]:
df.head (10)

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
5,9,1,2003,2003m01,2,1,Rio de Janeiro,3304557,Capital,1,...,NaN,NaN,36,3,0,0,0,0,554,3
6,10,1,2003,2003m01,2,1,Rio de Janeiro,3304557,Capital,1,...,NaN,NaN,40,2,3,0,0,0,593,3
7,12,1,2003,2003m01,19,1,Rio de Janeiro,3304557,Capital,2,...,NaN,NaN,48,3,0,0,0,0,620,3
8,13,1,2003,2003m01,19,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,26,1,0,0,0,0,455,3
9,14,1,2003,2003m01,23,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,43,2,2,0,0,0,636,3

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37588 entries, 0 to 37587
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        37588 non-null  int64
 1   mes                         37588 non-null  int64
 2   ano                         37588 non-null  int64
 3   mes_ano                     37588 non-null  object
 4   aisp                        37588 non-null  int64
 5   risp                        37588 non-null  int64
 6   munic                       37588 non-null  object
 7   mcirc                       37588 non-null  int64
 8   regiao                      37588 non-null  object
 9   hom_doloso                  37588 non-null  int64
 10  lesao_corp_morte            37588 non-null  int64
 11  latrocinio                  37588 non-null  int64
 12  cvli                        37588 non-null  int64
 13  hom_por_interv_policial     37588 non-null  int64
 14  feminicidio                 2466 non-null   float64
 15  letalidade_violenta         37588 non-null  int64
 16  tentat_hom                  37588 non-null  int64
 17  tentativa_feminicidio       2466 non-null   float64
 18  lesao_corp_dolosa           37588 non-null  int64
 19  estupro                     37588 non-null  int64
 20  hom_culposo                 37588 non-null  int64
 21  lesao_corp_culposa          37588 non-null  int64
 22  roubo_transeunte            37588 non-null  int64
 23  roubo_celular               37588 non-null  int64
 24  roubo_em_coletivo           37588 non-null  int64
 25  roubo_rua                   37588 non-null  int64
 26  roubo_veiculo               37588 non-null  int64
 27  roubo_carga                 37588 non-null  int64
 28  roubo_comercio              37588 non-null  int64
 29  roubo_residencia            37588 non-null  int64
 30  roubo_banco                 37588 non-null  int64
 31  roubo_cx_eletronico         37569 non-null  float64
 32  roubo_conducao_saque        37588 non-null  int64
 33  roubo_apos_saque            37588 non-null  int64
 34  roubo_bicicleta             20199 non-null  float64
 35  outros_roubos               37588 non-null  int64
 36  total_roubos                37588 non-null  int64
 37  furto_veiculos              37588 non-null  int64
 38  furto_transeunte            37588 non-null  int64
 39  furto_coletivo              37588 non-null  int64
 40  furto_celular               37588 non-null  int64
 41  furto_bicicleta             20199 non-null  float64
 42  outros_furtos               37588 non-null  int64
 43  total_furtos                37588 non-null  int64
 44  sequestro                   37588 non-null  int64
 45  extorsao                    37588 non-null  int64
 46  sequestro_relampago         37588 non-null  int64
 47  estelionato                 37588 non-null  int64
 48  apreensao_drogas            37588 non-null  int64
 49  posse_drogas                32942 non-null  float64
 50  trafico_drogas              32942 non-null  float64
 51  apreensao_drogas_sem_autor  32942 non-null  float64
 52  recuperacao_veiculos        37588 non-null  int64
 53  apf                         32942 non-null  float64
 54  aaapai                      32942 non-null  float64
 55  cmp                         32942 non-null  float64
 56  cmba                        32942 non-null  float64
 57  ameaca                      37588 non-null  int64
 58  pessoas_desaparecidas       37588 non-null  int64
 59  encontro_cadaver            37588 non-null  int64
 60  encontro_ossada             37588 non-null  int64
 61  pol_militares_mortos_serv   37588 non-null  int64
 62  pol_civis_mortos_serv       37588 non-null  int64
 63  registro_ocorrencias        37588 non-null  int64
 64  fase                        37588 non-null  int64
dtypes: float64(12), int64(50), object(3)
memory usage: 18.6+ MB

In [41]:
df.shape

(37588, 65)

In [10]:
df.describe()

,cisp,mes,ano,aisp,risp,mcirc,hom_doloso,lesao_corp_morte,latrocinio,cvli,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
count,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000,3.758800e+04,37588.000000,37588.000000,37588.000000,37588.000000,...,32942.000000,32942.000000,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000
mean,81.724513,6.453203,2014.274822,20.152708,3.869932,3.791586e+06,2.916383,0.028227,0.095190,3.039800,...,8.737812,0.643737,41.372938,3.231244,0.360434,0.022906,0.013329,0.002208,445.302011,2.989066
std,48.320601,3.465985,6.677154,11.350589,2.011415,1.740552e+06,4.318591,0.180091,0.365578,4.433564,...,14.763082,1.642005,39.454679,4.167554,0.986363,0.180845,0.130521,0.049155,399.884405,0.103996
min,1.000000,1.000000,2003.000000,1.000000,1.000000,3.300100e+06,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,38.000000,3.000000,2009.000000,10.000000,2.000000,3.302601e+06,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,107.000000,3.000000
50%,78.000000,6.000000,2014.000000,20.000000,4.000000,3.304557e+06,1.000000,0.000000,0.000000,1.000000,...,5.000000,0.000000,30.000000,2.000000,0.000000,0.000000,0.000000,0.000000,371.000000,3.000000
75%,125.000000,9.000000,2020.000000,30.000000,6.000000,3.304557e+06,4.000000,0.000000,0.000000,4.000000,...,11.000000,1.000000,56.000000,5.000000,0.000000,0.000000,0.000000,0.000000,665.000000,3.000000
max,168.000000,12.000000,2026.000000,43.000000,7.000000,9.999999e+06,43.000000,6.000000,9.000000,43.000000,...,419.000000,60.000000,370.000000,191.000000,112.000000,10.000000,4.000000,2.000000,3185.000000,3.000000

In [42]:
df_capital = df.loc [df['munic'] == 'Rio de Janeiro']

df_capital

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37487,40,3,2026,2026m03,9,2,Rio de Janeiro,3304557,Capital,0,...,4.0,1.0,34,5,0,0,0,0,634,2
37488,41,3,2026,2026m03,18,2,Rio de Janeiro,3304557,Capital,0,...,6.0,2.0,48,5,0,0,0,0,909,2
37489,42,3,2026,2026m03,31,2,Rio de Janeiro,3304557,Capital,1,...,11.0,1.0,100,9,2,0,0,0,1382,2
37490,43,3,2026,2026m03,27,2,Rio de Janeiro,3304557,Capital,1,...,5.0,0.0,138,10,0,0,0,0,728,2
37491,44,3,2026,2026m03,3,1,Rio de Janeiro,3304557,Capital,1,...,6.0,1.0,42,6,0,0,0,0,870,2

In [43]:
df_cisp_capital = df.groupby('cisp') ['furto_celular'].sum().reset_index()

df_cisp_capital = df_cisp_capital.sort_values(by='furto_celular',  ascending=False)

df_aaapai_cisp = df.groupby('cisp') ['aaapai'].sum().reset_index()

df_cisp_capital

     cisp  furto_celular
12     16          25709
2       5          24695
10     14          18286
8      12          16929
0       1          15952
..    ...            ...
87    104             72
77     92             65
131   157             55
114   138             55
129   155             47

[138 rows x 2 columns]

In [44]:
df_cisp_capital = df_capital.groupby('cisp') ['furto_celular'].sum().reset_index()

df_cisp_capital = df_cisp_capital.sort_values(by='furto_celular',  ascending=False)

array_furto = np.array(df_cisp_capital['furto_celular'])
df_cisp_capital
print(array_furto)

[25709 24695 18286 16929 15952 15009 14571 14047 13992 12623 12092  8717
  8491  8023  7995  7532  7283  7109  6932  6907  6605  6526  6078  5714
  5555  5405  5248  4673  4627  4067  4005  4001  3729  3726  3076  2899
  2833  2301  1702  1578   402    73]

In [45]:
maximo = np.max(array_furto)
minimo = np.min(array_furto)
media = np.mean(array_furto)
mediana = np.median(array_furto)

print(f'O valor maximo é {maximo}')
print(f'O valor minimo é {minimo}')
print(f'O valor mediana é {mediana}')
print(f'O valor media é {media}')
q1 = np.percentile(array_furto, 25)
q2 = np.percentile(array_furto, 50)
q3 = np.percentile(array_furto, 75)
print(f'Q1: {q1}')
print(f'Q2: {q2}')
print(f'Q3: {q3}')

O valor maximo é 25709
O valor minimo é 73
O valor mediana é 6565.5
O valor media é 8040.880952380952
Q1: 4002.0
Q2: 6565.5
Q3: 11248.25

In [47]:
df_top25 = df_cisp_capital.loc[df_cisp_capital['furto_celular'] > q3]

print(df_top25)

    cisp  furto_celular
12    16          25709
2      5          24695
10    14          18286
8     12          16929
0      1          15952
5      9          15009
6     10          14571
14    18          14047
1      4          13992
28    32          12623
31    35          12092